#!/bin/bash
#version 0.95-4-N/HS

# Initiate 'boot' LED.
sudo pigpiod
echo "14" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio14/direction
echo "1" > /sys/class/gpio/gpio14/value
su pi

#You may share this script on the condition a reference to RaspberryConnect.com
#must be included in copies or derivatives of this script.

#A script to switch between a wifi network and a non internet routed Hotspot
#Works at startup or with a seperate timer or manually without a reboot
#Other setup required find out more at
#http://www.raspberryconnect.com

wifidev="wlan0" #device name to use. Default is wlan0.
#use the command: iw dev ,to see wifi interface name

createAdHocNetwork()
{
    echo "Creating Hotspot"
    ip link set dev "$wifidev" down
    ip a add 10.0.0.5/24 brd + dev "$wifidev"
    ip link set dev "$wifidev" up
    dhcpcd -k "$wifidev" >/dev/null 2>&1
    systemctl start dnsmasq
    systemctl start hostapd
}

#Create Hotspot
if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
then
       echo "Hostspot already active"
elif { wpa_cli status | grep "$wifidev"; } >/dev/null 2>&1
then
       echo "Cleaning wifi files and Activating Hotspot"
       wpa_cli terminate >/dev/null 2>&1
       ip addr flush "$wifidev"
       ip link set dev "$wifidev" down
       rm -r /var/run/wpa_supplicant >/dev/null 2>&1
       createAdHocNetwork
else #  activating Hotspot
       createAdHocNetwork
fi

# Start vein vis app
cd /home/pi/netstream
sudo python3 app.py